### ISSUE TITLE
你写的train.py是对的?

### ISSUE THREAD

**Issue by 409316492** [tthinking/ITFuse#2]

**Comment by 409316492** [comment]
def train(args, train_loader_ir, model, criterion_ir_Charbonnier, criterion_vi_Charbonnier,criterion_ssim_ir,criterion_ssim_vi,optimizer):
    losses = AverageMeter()
    losses_ir_Charbonnier = AverageMeter()
    losses_vi_Charbonnier = AverageMeter()
    losses_ssim_ir = AverageMeter()
    losses_ssim_vi= AverageMeter()
    weight = args.weight
    model.train()

    for i, (input,ir,vi)  in tqdm(enumerate(train_loader_ir), total=len(train_loader_ir)):

        if use_gpu:
            input = input.cuda()

            ir=ir.cuda()
            vi=vi.cuda()


        else:
            input = input
            ir=ir
            vi=vi

        out = model(ir,vi)

        loss_ir_Charbonnier = weight[0] * criterion_ir_Charbonnier(out, ir)     传参能对？

**Comment by tthinking** [comment]
?

**Comment by 409316492** [comment]
数据传参没有vi，你的其他项目就有
